name: Test

on:
  pull_request:
    branches:
    - main
  merge_group:
    types:
    - checks_requested
    branches:
    - main
  push:
    branches:
    - main

jobs:

  k6-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3